CITIES = [
    {
        "id": 1,
        "city_code": "Ha_Noi",
        "name": "Hà Nội",
        "country": "Vietnam",
        "lat": 21.0285,
        "lon": 105.8542,
        "population": 8400000,
        "is_capital": True,
    },
    {
        "id": 2,
        "city_code": "Tokyo",
        "name": "Tokyo",
        "country": "Japan",
        "lat": 35.6762,
        "lon": 139.6503,
        "population": 13960000,
        "is_capital": True,
    },
    {
        "id": 3,
        "city_code": "New_York",
        "name": "New York",
        "country": "USA",
        "lat": 40.7128,
        "lon": -74.0060,
        "population": 8336000,
        "is_capital": False,
    },
    {
        "id": 4,
        "city_code": "Paris",
        "name": "Paris",
        "country": "France",
        "lat": 48.8566,
        "lon": 2.3522,
        "population": 2161000,
        "is_capital": True,
    },
    {
        "id": 5,
        "city_code": "Sydney",
        "name": "Sydney",
        "country": "Australia",
        "lat": -33.8688,
        "lon": 151.2093,
        "population": 5312000,
        "is_capital": False,
    },
]
